新規投稿画面を作成した
satsuki-yabu/tenkue_board pull request #1
Opened 2020-10-02 11:45 UTC by satsuki-yabu

###新規投稿画面を作成しました。

2020-10-06 15:34 UTC, Al-79 commented
LGTMです！

2020-10-07 02:25 UTC, sew-sou19 requested changes
レビュー完了しました！

各指摘に対して、レスorスタンプで反応いただくようにしてください！
修正が完了したら再度レビューを依頼してくださいー。よろしくお願いします。

2020-10-07 02:25 UTC, sew-sou19 commented on app/controllers/users/registrations_controller.rb
> +  def configure_sign_up_params
ここのコメントアウト外した理由はなんでしょうか、、、？
新規投稿機能では不要な気がしますが、、、

2020-10-07 02:25 UTC, sew-sou19 commented on Gemfile.lock
>  GEM
これ`bundle update`されてますか？
修正は不要ですが、`bundle update`は意図しないgemのバージョンもあげてしまってエラーの原因になりかねないので、極力使わないようにしましょう。特にチーム開発でこれをやると、他のメンバーに迷惑をかけかねないので、、、

2020-10-07 02:25 UTC, sew-sou19 commented on app/controllers/users/sessions_controller.rb
> +  # def creates
ここも変更した理由はなんでしょうか、、？
不要な変更は元に戻しておきましょう

2020-10-07 02:25 UTC, sew-sou19 commented on app/models/user.rb
> +  validates :name, presence: true
今回のプルリクではuserモデルのバリデーションまでは不要です。
あとこれ前のチームのコードコピペされたりしてませんか、、、？（違ったら申し訳ありません🙏）

2020-10-07 02:25 UTC, sew-sou19 commented on app/views/layouts/_header.html.erb
> +      <%# ルートパスへのリンクを設置 %>
ルートパスへのリンクを設置しましょう。

2020-10-07 02:25 UTC, sew-sou19 commented on app/views/layouts/_header.html.erb
> +    <%# ログイン状態に応じて表記を変更すること %>
ログインの状態に応じて表記を変更しましょう

2020-10-07 02:25 UTC, sew-sou19 commented on config/routes.rb
> +    get 'users/sign_out', to: 'devise/sessions#destroy'
うーん、ここの記述不要かと思いますが、追加した理由ってなんでしょうか？？

2020-10-07 02:25 UTC, sew-sou19 commented on test/models/post_test.rb
> +require 'rails_helper'
テストまで書いていただいたんですね！
テストは別のチケットのタスクになってるので、今回はレビューしませんが、姿勢が◎です。
（ただしYAGNI原則には注意してください）

2020-10-07 02:25 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    def confirm_user
YAGNI原則に則りましょう。
実装しない機能については記述しないようにしてください。
https://qiita.com/sesame525/items/fb2cfb23d0d7ef593014

2020-10-07 09:09 UTC, satsuki-yabu commented on app/assets/javascripts/index.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
わかりました！
削除しました。

2020-10-07 09:11 UTC, satsuki-yabu commented on app/assets/stylesheets/index.scss
> +// Place all the styles related to the index controller here.
確認しました！
不要のため、削除しました。

2020-10-07 09:15 UTC, satsuki-yabu commented on app/controllers/posts_controller.rb
> +    end
ありがとうございます💦
インデント揃えました！

2020-10-07 09:17 UTC, satsuki-yabu commented on Gemfile.lock
>  GEM
すみません...！
bundle updateしました...

次回から気をつけます...

2020-10-07 12:13 UTC, sew-sou19 requested changes
いくつかもう少し対応をお願いします！！

2020-10-07 12:13 UTC, sew-sou19 commented on app/controllers/users/registrations_controller.rb
> +  def configure_sign_up_params
ここの確認お願いしますー！

2020-10-07 12:13 UTC, sew-sou19 commented on app/views/layouts/application.html.erb
> +      <% flash.each do |message_type, message| %>
ここのインデントも揃えましょう！
あとnotificationsが上だとレイアウトが崩れるか、フラッシュメッセージが表示されない可能性あるので、実際の画面で確認してみてください。フラッシュメッセージが出るならOKです

2020-10-07 12:13 UTC, sew-sou19 commented on config/routes.rb
> +    get 'users/sign_out', to: 'devise/sessions#destroy'
ここの確認もお願いしますー！

2020-10-07 13:01 UTC, sew-sou19 approved these changes
ひとまずLGTMです！
お疲れ様でした&細かくてごめんなさい！

2020-10-07 13:04 UTC, merged